# Generated by Django 6.0.4 on 2026-09-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('lightroom_url', models.URLField(blank=True)),
                ('gallery_type', models.CharField(choices=[('client', 'Client gallery'), ('showcase', 'General / portfolio gallery')], db_index=True, default='client', max_length=20)),
                ('showcase_category', models.CharField(blank=True, choices=[('weddings', 'Weddings'), ('proposals', 'Proposals'), ('love_stories', 'Love Stories'), ('other', 'Other')], default='love_stories', max_length=30)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('layout_slots', models.JSONField(blank=True, default=list)),
                ('is_private', models.BooleanField(default=True)),
                ('access_password', models.CharField(blank=True, default='1212', max_length=80)),
                ('allow_downloads', models.BooleanField(default=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='gallery_covers/')),
                ('love_stories_cover', models.ImageField(blank=True, null=True, upload_to='love_stories_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.album')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('album', models.ForeignKey(limit_choices_to={'gallery_type': 'showcase'}, on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='portfolio.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='portfolio.photo')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('album', 'photo'), name='unique_showcase_photo')],
            },
        ),
    ]
