# Generated by Django 6.0.4 on 2026-09-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_album_lightroom_url'),
        ('portfolio', '0004_alter_album_options_alter_photo_options'),
    ]

    operations = [
    ]
