# Generated by Django 6.0.4 on 2026-09-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_client_galleries'),
        ('portfolio', '0005_album_gallery_settings'),
        ('portfolio', '0005_merge_20260914_1624'),
    ]

    operations = [
    ]
