# Generated by Django 6.0.4 on 2026-09-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_album_gallery_type_showcase'),
        ('portfolio', '0006_merge_20260914_1644'),
    ]

    operations = [
    ]
